# Generated by Django 2.2.4 on 2022-07-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='ha.jpg', upload_to='profile_pics'),
        ),
    ]
