# Generated by Django 2.2.4 on 2022-07-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0019_auto_20220728_1259'),
        ('accounts', '0007_auto_20220727_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='photo.Photo'),
            preserve_default='True',
        ),
    ]
