# Generated by Django 2.2.4 on 2022-05-18 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0005_auto_20220506_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='favorite',
        ),
        migrations.AddField(
            model_name='photo',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
