# Generated by Django 2.2.4 on 2022-05-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
