# Generated by Django 2.2.4 on 2022-05-20 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0008_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='down',
            field=models.ManyToManyField(blank=True, related_name='down_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='up',
            field=models.ManyToManyField(blank=True, related_name='up_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
