# Generated by Django 2.2.4 on 2022-07-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_auto_20220520_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='ha.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
