# Generated by Django 2.2.4 on 2022-07-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
