# Generated by Django 2.2.4 on 2022-07-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='profile_img',
            field=models.ImageField(default='', upload_to='profile_pics'),
        ),
    ]
