# Generated by Django 2.2.4 on 2022-07-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_photo_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
