# Generated by Django 2.2.4 on 2022-07-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_auto_20220727_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='profile_img',
            field=models.ImageField(default='profile_pics/ha.jpg', upload_to='profile_pics/'),
        ),
    ]
