# Generated by Django 2.2.4 on 2022-07-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_auto_20220727_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profile_img',
        ),
    ]
