# Generated by Django 2.2.4 on 2022-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_auto_20220727_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='img',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.FileField(blank=True, upload_to='timeline_photo/%Y/%m/%d'),
        ),
    ]
