# Generated by Django 2.2.4 on 2022-07-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0018_auto_20220728_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='/media/profile_pics/ha.jpg', upload_to='timeline_photo/%Y/%m/%d'),
        ),
    ]
